### ISSUE TITLE
404 when fetching the installation tar

### ISSUE THREAD

**Issue by sebastian-jansson** [bytebase/install#13]
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/bytebase/install/main/install.sh)"

Results in:

Failed to download from https://github.com/bytebase/bytebase/releases/download/2.3.0/bytebase_2.3.0_Linux_x86_64.tar.gz, status code: 404

**Comment by sebastian-jansson** [comment]
![image](https://github.com/bytebase/install/assets/54795430/9414f00a-1083-475c-8d7d-262daafeb253)

Seems like the 2.3.0 release is missing the required files.

**Comment by lfkdev** [comment]
this repo is basically dead

**Comment by h3n4l** [comment]
> ![image](https://user-images.githubusercontent.com/54795430/249739661-9414f00a-1083-475c-8d7d-262daafeb253.png)
> 
> Seems like the 2.3.0 release is missing the required files.
Hi @sebastian-jansson , sorry for missing the issue, release 2.3.0 lack the binary, the newest version had fixed it.

**Comment by h3n4l** [comment]
> this repo is basically dead, why is no one from bytebase fixing this critical issue since weeks?
> 
> @d-bytebase

Hi @lfkdev , sorry for missing this issue, we had fixed it via #14

**Comment by d-bytebase** [comment]
> this repo is basically dead, why is no one from bytebase fixing this critical issue since weeks?
> 
> @d-bytebase

Sorry, missed the message and notification somehow. Feel free to join discord and let us know there if we miss anything.
