### ISSUE TITLE
bytebase_2.11.0_darwin_arm64.tar.gz not exists

### ISSUE THREAD

**Issue by phoenixg** [bytebase/install#18]
OS: darwin
ARCH: arm64
Get bytebase latest version: 2.11.0
Downloading tarball into /var/folders/zp/kzyknyfn6y9czv3d2pvt79p40000gn/T/tmp.As7VahTyKb
Start downloading https://github.com/bytebase/bytebase/releases/download/2.11.0/bytebase_2.11.0_darwin_arm64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0      6      0 --:--:--  0:00:01 --:--:--     6
Failed to download from https://github.com/bytebase/bytebase/releases/download/2.11.0/bytebase_2.11.0_darwin_arm64.tar.gz,

**Comment by rcleveng** [comment]
Duplicate issue also at https://github.com/bytebase/bytebase/issues/9498
2.9.0 seems to be the last release with the darwin binaries

**Comment by phoenixg** [comment]
I can install it now. But after installation, and run `bytebase --demo test001`, using the demo account to login(邮箱:demo@example.com 密码:1024), it says: `The email or password is not valid.`
